export const TR = {
  common: {
    home: "Ana Sayfa",
    products: "Ürünler",
    cart: "Sepet",
    checkout: "Ödeme",
    login: "Giriş Yap",
    register: "Kayıt Ol",
    logout: "Çıkış Yap",
    search: "Ara...",
    addToCart: "Sepete Ekle",
    buyNow: "Hemen Satın Al",
    viewAll: "Tümünü Gör",
    loading: "Yükleniyor...",
    error: "Bir hata oluştu",
    save: "Kaydet",
    cancel: "İptal",
    delete: "Sil",
    edit: "Düzenle",
    close: "Kapat",
    back: "Geri",
    next: "İleri",
    previous: "Önceki",
    submit: "Gönder",
    required: "Zorunlu alan",
  },
  product: {
    roastLevel: "Kavurma Derecesi",
    origin: "Menşei",
    weight: "Ağırlık",
    stock: "Stok",
    outOfStock: "Stokta Yok",
    inStock: "Stokta Var",
    sku: "Ürün Kodu",
    description: "Açıklama",
    reviews: "Değerlendirmeler",
    addReview: "Değerlendirme Ekle",
    flavorNotes: "Tat Notaları",
    featured: "Öne Çıkan",
    newArrivals: "Yeni Ürünler",
    bestSellers: "Çok Satanlar",
  },
  cart: {
    empty: "Sepetiniz boş",
    emptyDescription: "Sepetinize henüz ürün eklemediniz.",
    subtotal: "Ara Toplam",
    shipping: "Kargo",
    shippingFree: "Ücretsiz",
    total: "Toplam",
    continueShopping: "Alışverişe Devam Et",
    proceedToCheckout: "Ödemeye Geç",
    quantity: "Adet",
    remove: "Kaldır",
    update: "Güncelle",
  },
  checkout: {
    title: "Ödeme",
    shipping: "Teslimat Bilgileri",
    payment: "Ödeme",
    review: "Sipariş Özeti",
    placeOrder: "Siparişi Tamamla",
    processing: "İşleniyor...",
    success: "Siparişiniz başarıyla oluşturuldu!",
    orderNumber: "Sipariş Numarası",
  },
  address: {
    title: "Başlık",
    firstName: "Ad",
    lastName: "Soyad",
    phone: "Telefon",
    address: "Adres",
    city: "İl",
    district: "İlçe",
    postalCode: "Posta Kodu",
    addNew: "Yeni Adres Ekle",
    savedAddresses: "Kayıtlı Adresler",
    setDefault: "Varsayılan Yap",
  },
  order: {
    myOrders: "Siparişlerim",
    orderNumber: "Sipariş No",
    orderDate: "Sipariş Tarihi",
    orderStatus: "Sipariş Durumu",
    trackOrder: "Sipariş Takip",
    orderDetails: "Sipariş Detayı",
    items: "Ürünler",
    status: {
      PENDING: "Beklemede",
      CONFIRMED: "Onaylandı",
      PREPARING: "Hazırlanıyor",
      SHIPPED: "Kargoya Verildi",
      DELIVERED: "Teslim Edildi",
      CANCELLED: "İptal Edildi",
      REFUNDED: "İade Edildi",
    },
    paymentStatus: {
      PENDING: "Ödeme Bekleniyor",
      PAID: "Ödendi",
      FAILED: "Ödeme Başarısız",
      REFUNDED: "İade Edildi",
    },
  },
  auth: {
    email: "E-posta",
    password: "Şifre",
    confirmPassword: "Şifre Tekrar",
    name: "Ad Soyad",
    rememberMe: "Beni Hatırla",
    forgotPassword: "Şifremi Unuttum",
    noAccount: "Hesabınız yok mu?",
    hasAccount: "Zaten hesabınız var mı?",
    loginTitle: "Giriş Yap",
    registerTitle: "Kayıt Ol",
    loginButton: "Giriş Yap",
    registerButton: "Kayıt Ol",
  },
  account: {
    myAccount: "Hesabım",
    profile: "Profil",
    orders: "Siparişlerim",
    addresses: "Adreslerim",
    settings: "Ayarlar",
    logout: "Çıkış Yap",
  },
  admin: {
    dashboard: "Panel",
    products: "Ürünler",
    orders: "Siparişler",
    users: "Kullanıcılar",
    categories: "Kategoriler",
    coupons: "Kuponlar",
    settings: "Ayarlar",
    addProduct: "Ürün Ekle",
    editProduct: "Ürün Düzenle",
    totalSales: "Toplam Satış",
    totalOrders: "Toplam Sipariş",
    totalUsers: "Toplam Kullanıcı",
    totalProducts: "Toplam Ürün",
  },
  validation: {
    emailRequired: "E-posta adresi gerekli",
    emailInvalid: "Geçerli bir e-posta adresi girin",
    passwordRequired: "Şifre gerekli",
    passwordMin: "Şifre en az 8 karakter olmalı",
    passwordMatch: "Şifreler eşleşmiyor",
    nameRequired: "Ad soyad gerekli",
    phoneRequired: "Telefon numarası gerekli",
    phoneInvalid: "Geçerli bir telefon numarası girin",
    addressRequired: "Adres gerekli",
    cityRequired: "İl seçimi gerekli",
    districtRequired: "İlçe seçimi gerekli",
  },
};

export const ROAST_LEVELS = [
  { value: "light", label: "Açık Kavurma" },
  { value: "medium", label: "Orta Kavurma" },
  { value: "medium-dark", label: "Orta-Koyu Kavurma" },
  { value: "dark", label: "Koyu Kavurma" },
];

export const TURKISH_CITIES = [
  "Adana",
  "Adıyaman",
  "Afyonkarahisar",
  "Ağrı",
  "Amasya",
  "Ankara",
  "Antalya",
  "Artvin",
  "Aydın",
  "Balıkesir",
  "Bilecik",
  "Bingöl",
  "Bitlis",
  "Bolu",
  "Burdur",
  "Bursa",
  "Çanakkale",
  "Çankırı",
  "Çorum",
  "Denizli",
  "Diyarbakır",
  "Edirne",
  "Elazığ",
  "Erzincan",
  "Erzurum",
  "Eskişehir",
  "Gaziantep",
  "Giresun",
  "Gümüşhane",
  "Hakkari",
  "Hatay",
  "Isparta",
  "Mersin",
  "İstanbul",
  "İzmir",
  "Kars",
  "Kastamonu",
  "Kayseri",
  "Kırklareli",
  "Kırşehir",
  "Kocaeli",
  "Konya",
  "Kütahya",
  "Malatya",
  "Manisa",
  "Kahramanmaraş",
  "Mardin",
  "Muğla",
  "Muş",
  "Nevşehir",
  "Niğde",
  "Ordu",
  "Rize",
  "Sakarya",
  "Samsun",
  "Siirt",
  "Sinop",
  "Sivas",
  "Tekirdağ",
  "Tokat",
  "Trabzon",
  "Tunceli",
  "Şanlıurfa",
  "Uşak",
  "Van",
  "Yozgat",
  "Zonguldak",
  "Aksaray",
  "Bayburt",
  "Karaman",
  "Kırıkkale",
  "Batman",
  "Şırnak",
  "Bartın",
  "Ardahan",
  "Iğdır",
  "Yalova",
  "Karabük",
  "Kilis",
  "Osmaniye",
  "Düzce",
];

export const SHIPPING_COST = 29.9;
export const FREE_SHIPPING_THRESHOLD = 250;
